---
title: "Partner Performance Report"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,  warning = FALSE)
```
```{r load_packages, include=FALSE,message=F, warning=F}
library(tidyverse)
library(formattable)
library(knitr)
library(xtable)
library(pander)
```
## FY2017 


```{r load_target_and_mapping,message=F, warning=F}

rawdata <- read_tsv("BasicGraphics/data/ICPI_FactView_Site_IM_Haiti_20170515_v1_1.txt")
names(rawdata) <- tolower(names(rawdata))
old_mechanism <- c("FOSREF","PIH","CDS","TBD2","Catholic Medical Mission Board","University of Maryland","Health Service Delivery",
                   "GHESKIO 0545","POZ","GHESKIO 541","ITECH 1331","University of Miami","Dedup","ITECH 549")
fy2017_target <- rawdata %>%
                filter(snu1 != "_Military Haiti") %>%
                filter(indicator %in% c("TX_NEW","HTS_TST","HTS_TST_POS","TX_CURR")) %>%
                filter(!(implementingmechanismname %in% old_mechanism)) %>%
                filter(disaggregate == "Total Numerator") %>%
                filter(indicatortype == "DSD") %>% 
                filter(typefacility == "Y") %>%
                filter(numeratordenom == "N") %>%
                select(facility,implementingmechanismname,indicator,fy2017_targets) %>%
                group_by(facility,implementingmechanismname,indicator) %>%
                summarise( FY17TARGET = sum(fy2017_targets, na.rm= TRUE))
               
# load site_mapping
mapping <- read_csv("site_mapping.csv")
```


```{r load_prepare_testing_data,message=F, warning=F}
patient_cdv <-  read_csv("mesi_report_cdv.csv", skip =1)
names(patient_cdv)  <-  make.names(names(patient_cdv))
patient_cdv <- patient_cdv %>% select(RESEAU, INSTITUTION,TOTAL)
patient_cdv <- inner_join(patient_cdv,mapping, by = c("INSTITUTION" = "Facility.MESI"))
patient_cdv <- filter(patient_cdv,!is.na(INSTITUTION))

hts_target <- filter(fy2017_target, indicator == "HTS_TST" & FY17TARGET > 0)
hts_target <- left_join(hts_target,patient_cdv,by = c("facility"="Facility.DATIM"))

hts_target[which(hts_target$facility == "Centre Jeunes Plaine du Cul-de-Sac"),
       c("implementingmechanismname")] <-  "FOSREF 1925"
hts_target[which(hts_target$facility == "Centre Lakay de Ouanaminthe"),
           c("implementingmechanismname")] <-  "Linkages"

hts_target <- mutate(hts_target,performance = ifelse(FY17TARGET == 0, 0, TOTAL/FY17TARGET))
hts_target$performance <- percent(hts_target$performance, digits= 2L )

hts_target <- hts_target %>% select(facility,mechanism = implementingmechanismname,
                                    indicator,FY17Results = TOTAL, FY17TARGET,performance)
```

```{r load_prepare_tx_new_data,message=F, warning=F}
patient_enrolles <- read_csv("mesi_report_nouveau_enrolles.csv", skip = 1)
names(patient_enrolles) <- make.names(names(patient_enrolles))
names(patient_enrolles)[11] <- "TOTAL"
patient_enrolles <- patient_enrolles %>% select(RESEAU, INSTITUTION,TOTAL)
patient_enrolles <- filter(patient_enrolles,!is.na(INSTITUTION))

patient_enrolles <- inner_join(patient_enrolles,mapping, by = c("INSTITUTION" = "Facility.MESI"))
tx_new_target <- filter(fy2017_target, indicator == "TX_NEW" & FY17TARGET > 0)

tx_new_target <- left_join(tx_new_target,patient_enrolles,by = c("facility"="Facility.DATIM"))

tx_new_target[which(tx_new_target$facility == "Centre Jeunes Plaine du Cul-de-Sac"),
           c("implementingmechanismname")] <-  "FOSREF 1925"
tx_new_target <- mutate(tx_new_target,performance = ifelse(FY17TARGET == 0, 0, TOTAL/FY17TARGET))
tx_new_target$performance <- percent(tx_new_target$performance, digits= 2L )

tx_new_target <- tx_new_target %>% select(facility,mechanism = implementingmechanismname,
                                    indicator,FY17Results = TOTAL, FY17TARGET,performance)
```

```{r load_prepare_tx_curr_data,message=F, warning=F}
patient_actifs <- read_csv("mesi_report_actifs.csv", skip = 1)
names(patient_actifs) <- make.names(names(patient_actifs))
patient_actifs <-  patient_actifs %>% select(RESEAU,INSTITUTION,TOTAL)
patient_actifs <- filter(patient_actifs,!is.na(INSTITUTION))
patient_actifs <- inner_join(patient_actifs,mapping, by = c("INSTITUTION" = "Facility.MESI"))
tx_curr_target <- filter(fy2017_target, indicator == "TX_CURR" & FY17TARGET > 0)
tx_curr_target <- left_join(tx_curr_target,patient_actifs,by = c("facility"="Facility.DATIM"))

tx_curr_target[which(tx_curr_target$facility == "Centre Jeunes Plaine du Cul-de-Sac"),
              c("implementingmechanismname")] <-  "FOSREF 1925"
tx_curr_target <- mutate(tx_curr_target,performance = ifelse(FY17TARGET == 0, 0, TOTAL/FY17TARGET))
tx_curr_target$performance <- percent(tx_curr_target$performance, digits= 2L )

tx_curr_target <- tx_curr_target %>% select(facility,mechanism = implementingmechanismname,
                                          indicator,FY17Results = TOTAL, FY17TARGET,performance)
```


```{r load_prepare_hts_tst_pos_data,message=F, warning=F}
patient_positifs <- read_csv("mesi_report_positifs.csv",skip =1)
names(patient_positifs) <-  make.names(names(patient_positifs))
patient_positifs <-  patient_positifs %>% select(RESEAU,INSTITUTION, TOTAL)
patient_positifs <- filter(patient_positifs,!is.na(INSTITUTION))
patient_positifs <- inner_join(patient_positifs,mapping, by = c("INSTITUTION" = "Facility.MESI"))
hts_pos_target <- filter(fy2017_target, indicator == "HTS_TST_POS")
hts_pos_target <- left_join(hts_pos_target,patient_positifs,by = c("facility"="Facility.DATIM"))
hts_pos_target[which(hts_pos_target$facility == "Centre Jeunes Plaine du Cul-de-Sac"),
               c("implementingmechanismname")] <-  "FOSREF 1925"
hts_pos_target <- mutate(hts_pos_target,performance = ifelse(FY17TARGET == 0, 0, TOTAL/FY17TARGET))
hts_pos_target$performance <- percent(hts_pos_target$performance, digits= 2L )

hts_pos_target <- hts_pos_target %>% select(facility,mechanism = implementingmechanismname,
                                            indicator,FY17Results = TOTAL, FY17TARGET,performance)
```



```{r load_prepare_hts_yield_data,message=F, warning=F}

```


```{r load_prepare_net_new_data,message=F, warning=F}
patient_actifs <- read_csv("mesi_report_actifs.csv", skip = 1)
names(patient_actifs) <- make.names(names(patient_actifs))
patient_actifs <-  patient_actifs %>% select(RESEAU,INSTITUTION,fy2017May =TOTAL)
patient_actifs <- filter(patient_actifs,!is.na(INSTITUTION))
patient_actifs <- inner_join(patient_actifs,mapping, by = c("INSTITUTION" = "Facility.MESI"))

fy2017_net_new <- rawdata %>%
    filter(indicator %in% c("TX_CURR")) %>%
    filter(snu1 != "_Military Haiti") %>%
    filter(disaggregate == "Total Numerator") %>%
    filter(indicatortype == "DSD") %>% 
    filter(typefacility == "Y") %>%
    filter(numeratordenom == "N") %>%
    select(facility,fy2016apr,fy2017_targets) %>%
    group_by(facility) %>%
    summarise( fy2016apr = sum(fy2016apr, na.rm = TRUE),
              fy2017targets = sum(fy2017_targets, na.rm = TRUE)) %>%
    mutate(fy17_net_new_target = fy2017targets - fy2016apr)

fy2017_net_new <- left_join(fy2017_net_new,patient_actifs,by = c("facility" = "Facility.DATIM"))
fy2017_net_new <- mutate(fy2017_net_new, fy2017May_net_new = fy2017May-fy2016apr)
```


```{r}

##merge all site files
fy2017_results <- rbind(hts_target,hts_pos_target,tx_new_target,tx_curr_target)
fy2017_results$performance <- percent(fy2017_results$performance, digits= 2L )

```

```{r siteperformancetable,message=F, warning=F}
cdc<- c("CDS 1528","CMMB 1970","FOSREF 1925","GHESKIO 1924",
                  "GHESKIO 1969","MSPP/UGP (National AIDS Strategic Plan)","PIH 1926")
print_partner <- function(data,p) {
   ind <- c("HTS_TST","HTS_TST_POS","TX_NEW","TX_CURR")
    for(i in 1:4) {
        
     tab <- filter(fy2017_results, mechanism == p & indicator == ind[i]) 
     tab <- select (tab,facility,FY17Results,FY17TARGET,performance)
     pandoc.header(" ", level = 3)
     pandoc.header(paste(ind[i], "performance by site"), level = 4)
     print(kable(tab,format = "html"))
    }
    
}

 
```


### `r cdc[1]`
```{r message=F, warning=F, results= "asis"}

print_partner(fy2017_results,cdc[1])

```

### `r cdc[2]`
```{r message=F, warning=F, results= "asis"}

print_partner(fy2017_results,cdc[2])

```
***

### `r cdc[3]`
```{r message=F, warning=F, results= "asis"}

print_partner(fy2017_results,cdc[3])

```


### `r cdc[4]`
```{r message=F, warning=F, results= "asis"}

print_partner(fy2017_results,cdc[4])

```


### `r cdc[5]`
```{r message=F, warning=F, results= "asis"}

print_partner(fy2017_results,cdc[5])

```


### `r cdc[6]`
```{r message=F, warning=F, results= "asis"}

print_partner(fy2017_results,cdc[6])

```



### `r cdc[7]`
```{r message=F, warning=F, results= "asis"}

print_partner(fy2017_results,cdc[7])

```

